# Generated by Django 4.2.5 on 2023-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='image/avatar/avatar.png', upload_to='avatar'),
        ),
    ]
