# Generated by Django 4.2.5 on 2023-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_on',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
