# Generated by Django 4.2.5 on 2023-09-29 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_transaction_date_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_pub',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 9, 29, 13, 58, 5, 378880, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
