# Generated by Django 4.2.5 on 2023-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_transaction_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/avatar.png', upload_to='avatar'),
        ),
    ]
